_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  aggregator: 0
  asset_injector: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  book: 0
  breakpoint: 0
  charts: 0
  charts_billboard: 0
  charts_c3: 0
  charts_highcharts: 0
  ckeditor: 0
  color: 0
  comment: 0
  commerce: 0
  commerce_cart: 0
  commerce_checkout: 0
  commerce_number_pattern: 0
  commerce_order: 0
  commerce_price: 0
  commerce_product: 0
  commerce_store: 0
  components: 0
  config: 0
  contact: 0
  contentimport: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  emulsify_twig: 0
  entity: 0
  entity_reference_revisions: 0
  exif_orientation: 0
  field: 0
  field_inheritance: 0
  field_ui: 0
  file: 0
  filter: 0
  formatter_suite: 0
  geofield: 0
  geofield_map: 0
  geofield_map_extras: 0
  google_analytics: 0
  google_analytics_reports: 0
  google_analytics_reports_api: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  language: 0
  leaflet: 0
  leaflet_markercluster: 0
  leaflet_views: 0
  link: 0
  linkit: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_google_cse: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  plyr: 0
  profile: 0
  quickedit: 0
  rdf: 0
  recurring_events: 0
  recurring_events_views: 0
  redirect: 0
  responsive_image: 0
  robotstxt: 0
  search: 0
  shortcut: 0
  social_media_links: 0
  standard: 0
  state_machine: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  user: 0
  views_infinite_scroll: 0
  views_ui: 0
  webform: 0
  webform_node: 0
  webform_submission_export_import: 0
  webform_submission_log: 0
  webform_ui: 0
  xmlsitemap_engines: 0
  pathauto: 1
  xmlsitemap: 1
  content_translation: 10
  views: 10
theme:
  bartik: 0
  seven: 0
  olivero: 0
  claro: 0
  stable: 0
  classy: 0
  bootstrap5: 0
  gin: 0
  alivero: 0
profile: standard
