entity_type_groups:
  media:
    image:
      basic: basic
  node:
    video:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
  taxonomy_term:
    tags:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
      google_cse: google_cse
tag_trim_method: beforeValue
tag_trim_maxlength:
  metatag_maxlength_abstract: null
  metatag_maxlength_title: null
  metatag_maxlength_description: null
  metatag_maxlength_og_site_name: null
  metatag_maxlength_og_description: null
  metatag_maxlength_og_title: null
  metatag_maxlength_twitter_cards_title: null
  metatag_maxlength_twitter_cards_label2: null
  metatag_maxlength_twitter_cards_label1: null
  metatag_maxlength_twitter_cards_description: null
tag_scroll_max_height: ''
